name: CI

on:
  push:
    branches: [ new-handover ]
  pull_request:
    branches: [ new-handover ]

jobs:
  build-and-run:
    name: ${{ matrix.compiler.name }} ${{ matrix.compiler.version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - { name: gcc, version: 13 }
          - { name: clang, version: 18 }

    steps:
    - uses: actions/checkout@v4

    - name: Set up ${{ matrix.compiler.name }}
      uses: egor-tensin/setup-gcc@v1
      with:
        version: ${{ matrix.compiler.version }}
        platform: x64
      if: matrix.compiler.name == 'gcc'

    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: ${{ matrix.compiler.version }}
        platform: x64
      if: matrix.compiler.name == 'clang'

    - name: Configure and build
      run: |
        ./ns3 configure --enable-examples --enable-tests --build-profile=release
        ./ns3 build

    - name: Run simulation
      run: ./ns3 run mmwave-simple-epc

    - name: Archive build logs
      uses: actions/upload-artifact@v4
      with:
        name: build-logs-${{ matrix.compiler.name }}-${{ matrix.compiler.version }}
        path: build/
        if-no-files-found: error

  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: 18
        platform: x64

    - name: Run clang-tidy
      run: |
        find src/mmwave -path src/mmwave/examples -prune -o -path src/mmwave/test -prune -o -name "*.cc" -print0 | xargs -0 clang-tidy -p build --warnings-as-errors=*
